guild_id: "YOUR_GUILD"

bot:
  token: "YOUR_TOKEN"
  status: "%version% %online%/%maxonline% players online"
  prefix: "mc/"
  modules:
    remote-execution: true

format:
  minecraft:
    user: "&7[D]&f <%user%> %message%"
  discord:
    user: "%message%"
    system: "**%message%**"

webhook:
  urls:
    - "WEBHOOK_URL"
  appearance:
    system:
      name: "Server"
      avatar: "https://minotar.net/avatar/Herobrine"
    player:
      name: "%user%"
      avatar: "https://minotar.net/avatar/%user%"

whitelist:
  users:
    # - "652853083176697866"
  roles:
    # - "652853083176697866"
  channels:
    # - "652853083176697866"

permissions:
  default:
    - "bukkit.command.tps"
    - "bukkit.command.plugins"
    - "bukkit.command.version"