name: McMirror
version: 3.0.0
author: twonglebat
main: dev.trinitrotoluene.mcmirror.MirrorPlugin
api-version: 1.14
description: A no-nonsense and robust Minecraft <-> Discord bridge.

commands:
  mirror:
    description: Root command for managing MC Mirror.
    usage: /mirror help
  mirrorenable:
    description: Enable message mirroring.
    usage: /mcenable
    permission: mcmirror.*
  mirrordisable:
    description: Disable message mirroring, leaving the underlying connection with Discord intact. Use this if you're turning the plugin off temporarily.
    usage: /mcdisable
    permission: mcmirror.*
  mirrorkill:
    description: Kills the underlying connection to Discord. Useful during Discord outages and for saving resources when the plugin is disabled.
    usage: /mcstop
    permission: mcmirror.*
  mirrorconnect:
    description: Establishes a new connection to Discord.
    usage: /mcstart
    permission: mcmirror.*
  mirrorstatus:
    description: Prints the current status of the Discord connection.
    usage: /mcstatus
    permission: mcmirror.status

permissions:
# Aggregated nodes
  mcmirror.*:
    default: op
    children:
      mcmirror.manage: true
      mcmirror.mirror: true
  mcmirror.manage:
    default: op
    children:
      mcmirror.enable: true
      mcmirror.disable: true
      mcmirror.disconnect: true
      mcmirror.connect: true
      mcmirror.status: true

# Management nodes
  mcmirror.enable:
    default: op
  mcmirror.disable:
    default: op
  mcmirror.disconnect:
    default: op
  mcmirror.connect:
    default: op
  mcmirror.status:
    default: op
# Public nodes
  mcmirror.mirror:
    default: true