name: McMirror
version: 3.0.0
author: twonglebat
main: dev.trinitrotoluene.mcmirror.MirrorPlugin
api-version: 1.14
description: A no-nonsense and robust Minecraft <-> Discord bridge.

commands:
  mirrorenable:
    description: Enable message mirroring.
    usage: /mcenable
    permission: mcmirror.*
  mirrordisable:
    description: Disable message mirroring, leaving the underlying connection with Discord intact. Use this if you're turning the plugin off temporarily.
    usage: /mcdisable
    permission: mcmirror.*
  mirrorkill:
    description: Kills the underlying connection to Discord. Useful during Discord outages and for saving resources when the plugin is disabled.
    usage: /mcstop
    permission: mcmirror.*
  mirrorconnect:
    description: Establishes a new connection to Discord.
    usage: /mcstart
    permission: mcmirror.*
  mirrorstatus:
    description: Prints the current status of the Discord connection.
    usage: /mcstatus
    permission: mcmirror.status


permissions:
  mcmirror.*:
    default: op
    children:
      mirrorstatus: true

  mcmirror.status:
    default: op
  mcmirror.mirror:
    default: true